In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('../data/raw/Zomato.csv')
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
data.shape

(1000, 7)

In [4]:
data

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Cafe Vivacity,Yes,No,3.8/5,87,650,Cafes
1,Chatar Patar,No,No,3.7/5,59,330,Dining
2,Timepass Dinner,Yes,No,3.8/5,275,540,Buffet
3,T3H Cafe,No,No,3.9/5,85,300,Cafes
4,Faasos,Yes,No,4.2/5,385,500,other
...,...,...,...,...,...,...,...
995,Spice 9,No,No,3.4/5,8,300,Dining
996,The Big O Bakes,No,No,4.0/5,61,270,Dining
997,Naveen Kabab & Biriyani Mane,No,No,3.2/5,10,300,Dining
998,Dharwad Line Bazaar Mishra Pedha,No,No,3.4/5,0,150,Dining
999,Kotian Karavali Restaurant,No,No,3.5/5,10,300,Dining

In [5]:
data.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='str')

In [6]:
data.describe()

             votes  approx_cost(for two people)
count  1000.000000                  1000.000000
mean    256.382000                   419.340000
std     631.161438                   226.604753
min       0.000000                    90.000000
25%       6.000000                   220.000000
50%      43.500000                   390.000000
75%     218.250000                   600.000000
max    5357.000000                  1040.000000

In [7]:
data.duplicated().sum()

np.int64(220)

In [8]:
data.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
approx_cost(for two people)    0
listed_in(type)                0
dtype: int64

In [9]:
print(data.columns.tolist())

['name', 'online_order', 'book_table', 'rate', 'votes', 'approx_cost(for two people)', 'listed_in(type)']

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         1000 non-null   str
 1   online_order                 1000 non-null   str
 2   book_table                   1000 non-null   str
 3   rate                         1000 non-null   str
 4   votes                        1000 non-null   int64
 5   approx_cost(for two people)  1000 non-null   int64
 6   listed_in(type)              1000 non-null   str
dtypes: int64(2), str(5)
memory usage: 54.8 KB

In [11]:
# percentage of null or missing values
missing_df = pd.DataFrame({
    "Missing Values": data.isnull().sum(),
    "Missing Percentage": (data.isnull().sum() / len(data)) * 100
})

missing_df

                             Missing Values  Missing Percentage
name                                      0                 0.0
online_order                              0                 0.0
book_table                                0                 0.0
rate                                      0                 0.0
votes                                     0                 0.0
approx_cost(for two people)               0                 0.0
listed_in(type)                           0                 0.0

In [12]:
data.duplicated().sum()

np.int64(220)